// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Pagination struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
}

type Person struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Surname     string `json:"surname"`
	Patronymic  string `json:"patronymic"`
	Age         int    `json:"age"`
	Gender      string `json:"gender"`
	Nationality string `json:"nationality"`
}

type PersonFilter struct {
	Gender      string `json:"gender"`
	Nationality string `json:"nationality"`
}

type PersonInput struct {
	Name        string `json:"name"`
	Surname     string `json:"surname"`
	Patronymic  string `json:"patronymic"`
	Age         int    `json:"age"`
	Gender      string `json:"gender"`
	Nationality string `json:"nationality"`
}
